 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Alarms", "plasma-windowed -graphicssystem raster org.kde.active.alarms", "/usr/local/share/icons/hicolor/16x16/apps/kalarm-active.png" },
     {"Artha", "artha", "/usr/share/pixmaps/artha.png" },
     {"Docky", "docky", "/usr/share/icons/hicolor/16x16/apps/docky.svg" },
     {"Font Viewer", "gnome-font-viewer ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"KCalc", "kcalc", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/hicolor/16x16/apps/kwrite.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Synergy", "synergy", "///usr/share/icons/synergy.ico" },
     {"Xarchiver", "xarchiver ", "/usr/share/icons/hicolor/16x16/apps/xarchiver.png" },
     {"Xpad", "xpad"},
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"GNU Octave", "/usr/bin/octave --force-gui ", "///usr/share/octave/4.0.2/imagelib/octave-logo.svg" },
     {"Klavaro", "klavaro", "/usr/share/icons/hicolor/16x16/apps/klavaro.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"QtOctave", "qtoctave", "/usr/share/icons/hicolor/64x64/apps/qtoctave.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Quake III Arena", "/usr/bin/quake3", "///usr/share/pixmaps/quake3.xpm" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Agave", "agave", "/usr/share/icons/hicolor/16x16/apps/agave.png" },
     {"E-book Viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gpick", "gpick", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
     {"Image Viewer", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"Images", "active-filebrowser --resourceType=nfo:Image -graphicssystem raster ", "/usr/local/share/icons/hicolor/16x16/apps/active-image-viewer.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Pencil", "/usr/bin/pencil", "///usr/share/evolus-pencil/skin/classic/icon.svg" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Angelfish Web Browser", "angelfish"},
     {"AnyDesk", "anydesk", "/usr/share/icons/hicolor/16x16/apps/anydesk.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Browser", "active-webbrowser -graphicssystem raster ", "/usr/local/share/icons/hicolor/16x16/apps/active-web-browser.png" },
     {"Chrome App Launcher", "/opt/google/chrome/google-chrome --show-app-list"},
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Dropbox", "dropbox", "/usr/share/pixmaps/dropbox.png" },
     {"Firefox", "firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"JDownloader", "JDownloader", "/usr/share/icons/hicolor/16x16/apps/jdownloader.png" },
     {"KDE Connect Monitor", "plasmawindowed org.kde.kdeconnect --statusnotifier", "/usr/share/icons/hicolor/16x16/apps/kdeconnect.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"SSH AskPass", "/usr/bin/ssh-add"},
     {"Slack", "/usr/share/slack/slack ", "/usr/share/pixmaps/slack.png" },
     {"Telegram Desktop", "telegram -- ", "/usr/share/pixmaps/telegram.png" },
     {"Telegram Desktop", "/opt/telegram/Telegram -- ", "/usr/share/pixmaps/telegram.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "///usr/share/pixmaps/tor-browser-en.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"Uzbl Browser", "uzbl-browser ", "/usr/share/icons/hicolor/32x32/apps/uzbl.png" },
     {"Uzbl Tabbed", "uzbl-tabbed ", "/usr/share/icons/hicolor/32x32/apps/uzbl.png" },
     {"Viber", "/opt/viber/Viber", "///usr/share/pixmaps/viber.png" },
     {"Widget Strip", "plasma-widgetstrip"},
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY", "/usr/share/icons/hicolor/16x16/apps/computer.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"iptux", "iptux", "/usr/share/icons/hicolor/16x16/apps/ip-tux.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Books", "active-filebrowser --mimeTypes=application/epub+zip,application/pdf -graphicssystem raster "},
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"Edit E-book", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Tasque", "tasque", "/usr/share/icons/hicolor/16x16/apps/tasque.png" },
     {"WordNet", "wnb", "///usr/share/pixmaps/wordnet.png" },
     {"XMind", "XMind", "/usr/share/pixmaps/XMind.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Cuttlefish", "cuttlefish"},
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Giggle", "giggle ", "/usr/share/icons/hicolor/16x16/apps/giggle.png" },
     {"Java Mission Control", "/usr/lib/jvm/java-8-jdk/bin/jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java Monitoring and Management Console", "/usr/lib/jvm/java-8-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java VisualVM", "/usr/lib/jvm/java-8-jdk/bin/jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"MySQL Workbench", "mysql-workbench", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"Pencil", "/usr/bin/pencil", "///usr/share/evolus-pencil/skin/classic/icon.svg" },
     {"Plasma Theme Explorer", "plasmathemeexplorer", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"Plasmate", "plasmate", "/usr/share/icons/hicolor/16x16/apps/plasmagik.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Sublime Text 3 Dev", "subl3 ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"pgAdmin III", "/usr/bin/pgadmin3", "///usr/share/pgadmin3/pgAdmin3.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audio Mixer", "xfce4-mixer", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Cantata", "cantata "},
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Cheese.png" },
     {"Kodi media center", "kodi", "/usr/share/icons/hicolor/16x16/apps/kodi.png" },
     {"OSD Lyrics", "osdlyrics", "/usr/share/icons/hicolor/64x64/apps/osdlyrics.png" },
     {"OpenShot Video Editor", "openshot ", "/usr/share/pixmaps/openshot.svg" },
     {"Plasma Media Center", "plasmashell -ap org.kde.plasma.mediacenter"},
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Sonata", "sonata"},
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"About", "active-aboutapp -graphicssystem raster", "/usr/local/share/icons/hicolor/16x16/apps/active-about.png" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Compiz Fusion Icon", "fusion-icon", "/usr/share/icons/hicolor/22x22/apps/fusion-icon.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Dolphin", "dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Files", "active-filebrowser -graphicssystem raster ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KDE Connect Indicator", "indicator-kdeconnect", "/usr/share/icons/hicolor/16x16/apps/kdeconnect.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Q4Wine", "q4wine -b "},
     {"SSH AskPass", "/usr/bin/ssh-add"},
     {"Startup Disk Creator", "usb-creator-kde"},
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Virtual Machine Manager", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Yakuake", "yakuake", "/usr/share/icons/hicolor/16x16/apps/yakuake.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

